// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("mongodb+srv://mukesh2sahu786_db_user:VW9TtcU7wtFhH8nD@cluster0.6iiwe6j.mongodb.net/?appName=Cluster0"),
  },
});
